blank_issues_enabled: false
contact_links:
  - name: ❓ Support Question
    url: https://github.com/serversideup/amplitudejs/discussions/483
    about: Get friendly support from the community on our forum.

  - name: ✨ Request a feature
    url: https://github.com/serversideup/amplitudejs/discussions/484
    about: Learn how to request a new feature.

  - name: 🤵 Get Professional Support & Customizations
    url: https://serversideup.net/get-help/?quick_question=amplitudejs
    about: Skip the line and get priority support directly from the creators of AmplitudeJS.